### ISSUE TITLE
Add UDP support

### ISSUE THREAD

**Issue by Ullaakut** [nitrado/connqc#10]
It would be great to be able to do quality checking on UDP connections as well.

The system would have to be slightly more complex than TCP QC, since UDP connections are long lived and there are more things that can go wrong.

It could make sense to test two main things:

1/ Are we able to repeatedly create new connections with the UDP endpoint without errors? How long does the handshake take?
2/ Are we able to send and receive messages over the UDP connection? How much latency is there? Are some messages getting lost?

A simple approach could be to do it in a similar way to the TCP test, which is to create a connection, send a message, expect to receive it back, check latency, close connection. But it could also make sense to send multiple messages on the UDP socket instead of a single one.

A more interesting approach could be to send quite large amounts of data instead of a single probe message, to check for the bandwidth speed as well, since UDP is usually intended to send live data, in possibly large amounts.

**Comment by DrPsychick** [comment]
Sounds good. I would also start with a simple approach and just print the message when received (potentially out of order) and consider it lost when not received after a certain time.
